### ISSUE TITLE
Issues around tag highlighting

### ISSUE THREAD

**Issue by kenwheeler** [mxw/vim-jsx#76] opened 2015-12-11 15:37 UTC
While it appears that tag highlighting works when using the solarized colorscheme, if you check it out with almost any other colorscheme, identical .vimrc's , you will see that the highlighting is indeed wrong.

![screen shot 2015-12-11 at 9 47 26 am](https://cloud.githubusercontent.com/assets/286616/11747744/f18f906a-9ff2-11e5-937b-23b7b52af81d.png)

Reproduce:

- Use all the recommended settings in this repo (which I'm sure you are)
- Change the colorscheme to anything other than solarized (oceanicnext is a fun one)
- See that beginning and ending tags have different colors

Thanks!

**Comment by ksmithbaylor** [comment] 2015-12-11 22:30
I believe this is by design. `vim-jsx` uses vim's built-in XML highlighting under the hood, and this is the highlighting used for that. Try opening a plain xml file!

Personally, I like it. It took a bit of getting used to, but for me it's easier to visually identify blocks, especially with highly-nested component trees.

**Comment by kenwheeler** [comment] 2015-12-11 22:36
Thanks!

**Comment by knowbody** [comment] 2015-12-15 18:37
@ksmithbaylor interesting... But then having something like:

```
<Component />
```

should have `<` in blue and `/>` in red, right? Or is that just my logic?

**Comment by ksmithbaylor** [comment] 2015-12-15 18:42
That seems like it would make sense, but I guess vim treats self-closing tags as a single tag instead of an opening tag and a closing tag "combined". It would probably be better the way you suggest, but alas, vim.

**Comment by mxw** [comment] 2015-12-15 18:50
FWIW, if you find another XML highlighting package (say, on GitHub) that you prefer, it _might_ work with vim-jsx... so long as all the syntax elements have names which start with `xml`, and attribute values are `xmlString`s.  Unfortunately, syntax package authors are not known to match the naming schemes of the vim defaults :|

**Closed** 2016-01-24 04:52 UTC
