### ISSUE TITLE
Some keywords cause incorrect indentation

### ISSUE THREAD

**Issue by tandrewnichols** [mxw/vim-jsx#109] opened 2016-08-04 23:23 UTC
I read the README. I'm using vim-javascript-syntax.

I've discovered that I get some unusual indenting with vim-jsx enabled (the indenting is correct when I have the Plug declaration commented out and incorrect when not) when the keyword `default` is used as an object key. Arguably, `default` should not be used as a key without quotes, so I would understand if you ignored this issue, but node _does_ allow it. Here's a simplified use case:

```
var obj = {
  default: 'banana'
};
```

If I put the cursor at the end of the banana line, add a comma, and then hit enter, the next line indents so that my cursor lines up with the start of the string 'banana'. I.e.

```
var obj = {
  default: 'banana',
           I
};
```

where `I` is the cursor position. In fact, if there are _already_ other keys _after `default`, they get indented to align with 'banana' as well. E.g. before

```
var obj = {
  default: 'banana',
  foo: 'bar'
};
```

and after

```
var obj = {
  default: 'banana',
           foo: 'bar',
           I
};
```

where `I` is once again the cursor. If I wrap `default` in quotes, this doesn't occur. Here are some screenshots of my usage:

**Before (no quotes)**
<img width="681" alt="before" src="https://cloud.githubusercontent.com/assets/2755760/17421413/9c367c1a-5a77-11e6-815d-358a45be421a.png">

**After (no quotes)**
<img width="679" alt="after" src="https://cloud.githubusercontent.com/assets/2755760/17421425/a8c26b9c-5a77-11e6-8136-e2bee105d5b3.png">

**Before (with quotes)**
<img width="671" alt="before with quotes" src="https://cloud.githubusercontent.com/assets/2755760/17421568/c22d718e-5a78-11e6-9ce7-b0f7679f40ba.png">

**After (with quotes)**
<img width="672" alt="after with quotes" src="https://cloud.githubusercontent.com/assets/2755760/17421573/c8f7b36c-5a78-11e6-8096-9588f4afcf47.png">

Again, I recognize this might be a "Won't Fix," but I thought I'd at least open the issue. Thanks for the plugin!

**Comment by mxw** [comment] 2016-08-04 23:59
Are you sure this isn't an issue with `vim-javascript-syntax`?  I think that package is pretty stale; you might want to try one of the other ones.

**Comment by mxw** [comment] 2016-08-05 00:07
This seems unlikely to be vim-jsx, since JSX syntax shouldn't even be kicking in in a context where you don't have any JSX elements, in which case we'll fall back to the default indentation.  Further, `vim-javascript-syntax` isn't officially supported.  Closing out for now, but feel free to comment if you aren't able to determine that your issue is caused by `vim-javascript-syntax` (or by some other conflicting plugin—have you tried bisecting your `~/.vimrc`?).

**Closed by mxw** 2016-08-05 00:07 UTC

**Comment by tandrewnichols** [comment] 2016-08-05 01:50
It works fine with _just_ vim-javascript-syntax. It's only when I add `vim-jsx` that it indents weird.

**Comment by tandrewnichols** [comment] 2016-08-05 01:55
But in an interesting twist, it does work with vim-javascript. But I won't be using that package. The syntax definition causes the colors to be different, and I'm just too used to what I have.

**Comment by mxw** [comment] 2016-08-05 02:40
Does the problem actually manifest for your short text example?  Or only for in the full context of your screenshot?

**Comment by tandrewnichols** [comment] 2016-08-05 13:28
Yeah, for both.
